apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment-both
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: authservice-container
        image: aditya1113/authservice:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
          name: auth-port
        env:
        - name: URL
          valueFrom:
            secretKeyRef:
              name: service-secrets
              key: URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: service-secrets
              key: SECRET_KEY

      - name: userservice-container
        image: aditya1113/userservice:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8001
          name: user-port
        env:
        - name: URL
          valueFrom:
            secretKeyRef:
              name: service-secrets
              key: URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: service-secrets
              key: SECRET_KEY
