apiVersion: v1
kind: Service
metadata:
  name: nodejs-service-both
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
  - name: authservice-port
    protocol: TCP
    port: 80      
    targetPort: 8000  
    nodePort: 30001   
  - name: userservice-port
    protocol: TCP
    port: 81      
    targetPort: 8001  
    nodePort: 30002   
