name: Deploy to EC2 using docker

on:
  push:
    branches:
      - master

jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: build-push-docker-image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Server1/Dockerfile
          push: true
          tags: aditya1113/authservice:latest
      - name: build-push-docker-image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Server2/Dockerfile
          push: true
          tags: aditya1113/userservice:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Start Minikube
        run: |
          minikube start

      - name: Use Minikube Docker Daemon
        run: |
          eval $(minikube docker-env)

      - name: Deploy Updated Images to Minikube
        run: |
          kubectl set image deployment/auth-deployment auth-container=aditya1113/authservice:latest
          kubectl rollout restart deployment auth-deployment
          kubectl rollout status deployment auth-deployment


      
        